### PR TITLE
Fix importing without CUDA

### PR DESCRIPTION
**Pull request by wdphy16**
We need to catch the exception when CUDA is not found.

Now I've tested both on Windows and Linux, and both with and without CUDA, using the example script in `README.md`.

When I have time maybe I can help set up CI for this repo.

### CODE REVIEW

**Comment by PhilipVinc** [comment]
Please add at least some barebone import tests.
I don't want to break everything again

**Comment by PhilipVinc** [comment]
The failure is because that tester is running oldest dependency versions, but numba 0.52 was not available for python 3.9

Just run macos on py3.8 and ubuntu on 3.9

**Comment by wdphy16** [comment]
Also, do you think we need to run codecov here? If we don't test with CUDA, a lot of code path will not be covered.

**Comment by PhilipVinc** [comment]
it's fine to run codecov.
Is it done?

**Comment by wdphy16** [comment]
Yes it's done as in NetKet, and in the next PR there should be diff coverage.

**Pull request merged**
